### ISSUE TITLE
Ability to see or sort new themes

### ISSUE THREAD

**Issue by Subtixx** [dracula/draculatheme.com#254]
I like having dracula theme everywhere. However I don't have time to keep up with all the repos and pull-requests. It would be really helpful if the website could have a page or option to see or sort for added date.

**Comment by luxonauta** [comment]
Thanks for the suggestion! 💜

But putting it into action is tricky with how things are set up now. It would require significant updates to an essential part of our system that helps us manage and display apps on the homepage. 🙃

✅ Because of this, we're focusing on other improvements that help everyone immediately. So, we're not moving forward with this suggestion at the moment.
